"""empty message

Revision ID: cc75ad9991ca
Revises: 8630841f5f59
Create Date: 2017-09-06 14:07:21.833091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc75ad9991ca'
down_revision = '8630841f5f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('locations', sa.Column('long', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'long')
    op.drop_column('locations', 'lat')
    # ### end Alembic commands ###
